CREATE TABLE IF NOT EXISTS logs (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	timestamp INTEGER NOT NULL, -- UNIX TIMESTAMP // 10
	action INTEGER NOT NULL, -- enum [ LOGIN, LOGOUT, MIMIC, DOWNLOAD, EDIT, BLOCKED ]
	user_id TEXT,
	user_name TEXT,
	level_id TEXT
);

